name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '6,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: build and publish
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        run: |-
          ./run.sh
